name: Cache Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: create-cache-dir
        run: mkdir -p cache-folder

      - name: cache-deps
        id: cache
        uses: actions/cache@v4
        with:
          path: cache-folder
          key: cache-326a757

      - name: prime-cache-326a757
        run: echo "Cache hit ${{ steps.cache.outputs.cache-hit }}"
